### ISSUE TITLE
Feature: New England rollups

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex-micro#1]
- [ ] Generate failing test or find failing test from Elex.
- [ ] Handle rollups in another loop.
- [ ] Benchmark.

**Comment by jeremyjbowers** [comment]
Getting closer.

```nose2 tests
........................................F.FFF.....F.
======================================================================
FAIL: test_ct_has_all_counties (tests.test_new_england_reporting_units.TestConnecticutRollups)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jbowers/src/nyt/elex-micro/tests/test_new_england_reporting_units.py", line 40, in test_ct_has_all_counties
    self.assertEqual(len(ct_counties), len(ct_mapped_counties))
AssertionError: 0 != 8

======================================================================
FAIL: test_number_of_reporting_units (tests.test_new_england_reporting_units.TestMaineEdgeCaseReportingUnits)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jbowers/src/nyt/elex-micro/tests/test_new_england_reporting_units.py", line 124, in test_number_of_reporting_units
    self.assertEqual(len(maine_results), 2)
AssertionError: 20 != 2

======================================================================
FAIL: test_one_state_level_unit (tests.test_new_england_reporting_units.TestMaineEdgeCaseReportingUnits)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jbowers/src/nyt/elex-micro/tests/test_new_england_reporting_units.py", line 133, in test_one_state_level_unit
    self.assertEqual(len(maine_state_level_units), 1)
AssertionError: 10 != 1

======================================================================
FAIL: test_one_subunit (tests.test_new_england_reporting_units.TestMaineEdgeCaseReportingUnits)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jbowers/src/nyt/elex-micro/tests/test_new_england_reporting_units.py", line 142, in test_one_subunit
    self.assertEqual(len(maine_subunits), 1)
AssertionError: 10 != 1

======================================================================
FAIL: test_number_of_counties (tests.test_results.TestMassRollupBug)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jbowers/src/nyt/elex-micro/tests/test_results.py", line 52, in test_number_of_counties
    self.assertEqual(len(mass_results), len(maps.FIPS_TO_STATE['MA']))
AssertionError: 0 != 14

----------------------------------------------------------------------
Ran 52 tests in 5.019s

FAILED (failures=5)```
